// <auto-generated />
namespace BankApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Fixtypeofbalance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixtypeofbalance));
        
        string IMigrationMetadata.Id
        {
            get { return "202304300839366_Fix type of balance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
